services:
    apache:
        build: .
        ports:
            - '8080:80'
        volumes:
            - ./www:/var/www/html
        depends_on:
            - mysql
            - mailpit

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: appuser
            MYSQL_PASSWORD: password123
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8081:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root

    mailpit:
        image: axllent/mailpit
        restart: always
        ports:
            - '1080:8025' # Interface Web
            - '1025:1025' # Port SMTP

volumes:
    db-data:
